Script update

diff --git a/scripts/assets-sync b/scripts/assets-sync
--- a/scripts/assets-sync
+++ b/scripts/assets-sync
@@ -12,7 +12,7 @@ die () {
 
 # Function for script usage
 usage () {
-    echo "Usage: $0 --srcstaccount <src_st_account> --srcstkey <src_st_key> --srcstcontainer <src_st_container> --dststaccount <dst_st_account> --dststkey <dst_st_key> --dststcontainer <dst_st_container> [--tmpdir <temp_directory>]"
+    echo "Usage: $0 --srcstaccount <src_st_account> --srcstkey <src_st_key> --srcstfileshare <src_st_fileshare> --srcpath <src_path> --dststaccount <dst_st_account> --dststkey <dst_st_key> --dststfileshare <dst_st_fileshare> --dstpath <dst_path>"
     exit 1
 }
 
@@ -24,42 +24,53 @@ while [[ $# -gt 0 ]]; do
     case "$1" in
         --srcstaccount) SRC_ST_ACCOUNT="$2"; shift 2;;
         --srcstkey) SRC_ST_KEY="$2"; shift 2;;
-        --srcstcontainer) SRC_ST_FILESYSTEM="$2"; shift 2;;
+        --srcstfileshare) SRC_ST_FILESHARE="$2"; shift 2;;
+        --srcpath) SRC_DIR="$2"; shift2;;
         --dststaccount) DST_ST_ACCOUNT="$2"; shift 2;;
         --dststkey) DST_ST_KEY="$2"; shift 2;;
-        --dststcontainer) DST_ST_FILESYSTEM="$2"; shift 2;;
-        --tmpdir) TMPDIR="$2"; shift 2;;
+        --dststfileshare) DST_ST_FILESHARE="$2"; shift 2;;
+        --dstpath) DST_DIR="$2"; shift 2;;
         --help) usage;;
         *) die "Unknown option: $1";;
     esac
 done
 
 # Validate required parameters
-if [[ -z "${SRC_ST_ACCOUNT:-}" || -z "${SRC_ST_KEY:-}" || -z "${SRC_ST_FILESYSTEM:-}" || -z "${DST_ST_ACCOUNT:-}" || -z "${DST_ST_KEY:-}" || -z "${DST_ST_FILESYSTEM:-}" ]]; then
+if [[ -z "${SRC_ST_ACCOUNT:-}" || -z "${SRC_ST_KEY:-}" || -z "${SRC_ST_FILESHARE:-}" || -z "${SRC_DIR:-}" || -z "${DST_ST_ACCOUNT:-}" || -z "${DST_ST_KEY:-}" || -z "${DST_ST_FILESHARE:-}" || -z "${DST_DIR:-}" || ]]; then
     die "Missing required parameters."
 fi
 
-# Set Azure storage environment variables (avoid exposing credentials in CLI)
+# Set destination storage credentials
 export AZURE_STORAGE_ACCOUNT="$SRC_ST_ACCOUNT"
 export AZURE_STORAGE_KEY="$SRC_ST_KEY"
 
-echo "===> Checking if source storage container exists."
-if ! az storage container exists --name "$SRC_ST_FILESYSTEM" --account-name "$SRC_ST_ACCOUNT" --account-key "$SRC_ST_KEY" --query "exists" --output tsv | grep -q "true"; then
-    die "Source container '$SRC_ST_FILESYSTEM' does not exist."
-fi
+# Check if Directory exists
+echo "===> Checking if Directory '$SRC_DIR' exists..."
+if az storage directory exists --account-name "$SRC_ST_ACCOUNT" --account-key "$SRC_ST_KEY" --share-name "$SRC_ST_FILESHARE" --name "$SRC_DIR" -o tsv | grep -q "True"; then
+    echo "===> Directory '$SRC_DIR' exists."
+else
+    die "Directory does not '$SRC_DIR' exists."
+fi  
 
 echo "===> Downloading files from source storage."
-if ! azcopy copy "https://$SRC_ST_ACCOUNT.blob.core.windows.net/$SRC_ST_FILESYSTEM/*" "$TMPDIR/" --recursive; then
-    die "Failed to download files from source container."
+if ! azcopy copy "https://$SRC_ST_ACCOUNT.blob.core.windows.net/$SRC_ST_FILESHARE/$SRC_DIR/*" "$TMPDIR/" --recursive; then
+    die "Failed to download files from source fileshare."
 fi
 
 # Set destination storage credentials
 export AZURE_STORAGE_ACCOUNT="$DST_ST_ACCOUNT"
 export AZURE_STORAGE_KEY="$DST_ST_KEY"
 
+echo "===> Checking if Directory '$DST_DIR' exists..."
+if az storage directory exists --share-name "$DST_ST_ACCOUNT" --name "$DST_DIR" -o tsv | grep -q "True"; then
+    echo "===> Directory '$DST_DIR' exists."
+else
+    die "Directory does not '$DST_DIR' exists."
+fi  
+
 echo "===> Uploading files to destination storage."
-if ! azcopy copy "$TMPDIR/*" "https://$DST_ST_ACCOUNT.blob.core.windows.net/$DST_ST_FILESYSTEM/" --recursive; then
-    die "Failed to upload files to destination container."
+if ! azcopy copy "$TMPDIR/*" "https://$DST_ST_ACCOUNT.blob.core.windows.net/$DST_ST_FILESHARE/$DST_DIR" --recursive; then
+    die "Failed to upload files to destination fileshare."
 fi
 
 # Cleanup temporary files
