Script updates

diff --git a/scripts/db-dump b/scripts/db-dump
--- a/scripts/db-dump
+++ b/scripts/db-dump
@@ -46,7 +46,7 @@ echo "===> Checking if Directory '$DIR' exists..."
 if az storage fs directory exists --file-system "$ST_CONTAINER" --name "$DIR" -o tsv | grep -q "True"; then
     echo "===> Directory '$DIR' exists."
 else
-    die "Failed to create Directory '$DIR'."
+    die "Directory '$DIR' does not exists."
 fi  
 
 echo "===> Checking if database '$DB_NAME' exists on host '$DB_HOST'."
@@ -69,9 +69,9 @@ if [[ "$DB_EXISTS" == "$DB_NAME" ]]; then
     echo "$BACKUP_FILE" > checkin.txt
 
     echo "===> Uploading database backup to Azure Blob Storage."
-    az storage blob upload --container-name "$ST_CONTAINER" --file "$BACKUP_FILE.tar.gz" --name "$BACKUP_FILE.tar.gz" --overwrite || die "Backup upload failed."
+    az storage blob upload --container-name "$ST_CONTAINER" --file "$BACKUP_FILE.tar.gz" --name "$DIR/$BACKUP_FILE.tar.gz" --overwrite || die "Backup upload failed."
     echo "===> Checkin file upload to Azure Blob Storage."
-    az storage blob upload --container-name "$ST_CONTAINER" --file "checkin.txt" --name "checkin.txt" --overwrite || die "Checkin file upload failed."
+    az storage blob upload --container-name "$ST_CONTAINER" --file "checkin.txt" --name "$DIR/checkin.txt" --overwrite || die "Checkin file upload failed."
     echo "===> Database backup '$BACKUP_FILE' uploaded successfully."
 
     # Cleanup
