Script updates

diff --git a/scripts/db-dump b/scripts/db-dump
--- a/scripts/db-dump
+++ b/scripts/db-dump
@@ -12,7 +12,7 @@ die () {
 
 # Function for script usage
 usage () {
-    echo "Usage: $0 --host <host> --admin <admin> --password <admin_pass> --dbname <db_name> --staccount <st_account> --stkey <st_key> --stcontainer <st_container>"
+    echo "Usage: $0 --host <host> --admin <admin> --password <admin_pass> --dbname <db_name> --staccount <st_account> --stkey <st_key> --stcontainer <st_container> --path <path>"
     exit 1
 }
 
@@ -25,14 +25,15 @@ while [[ $# -gt 0 ]]; do
         --dbname) DB_NAME="$2"; shift 2;;
         --staccount) ST_ACCOUNT="$2"; shift 2;;
         --stkey) ST_KEY="$2"; shift 2;;
-        --stcontainer) ST_FILESYSTEM="$2"; shift 2;;
+        --stcontainer) ST_CONTAINER="$2"; shift 2;;
+        --path) DIR="$2"; shift 2;;
         --help) usage;;
         *) die "Unknown option: $1";;
     esac
 done
 
 # Validate required parameters
-if [[ -z "${DB_HOST:-}" || -z "${DB_ADMIN:-}" || -z "${DB_PASS:-}" || -z "${DB_NAME:-}" || -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_FILESYSTEM:-}" ]]; then
+if [[ -z "${DB_HOST:-}" || -z "${DB_ADMIN:-}" || -z "${DB_PASS:-}" || -z "${DB_NAME:-}" || -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_CONTAINER:-}" || -z "${DIR:-}" ]]; then
     die "Missing required parameters."
 fi
 
@@ -40,15 +41,13 @@ fi
 export AZURE_STORAGE_ACCOUNT="$ST_ACCOUNT"
 export AZURE_STORAGE_KEY="$ST_KEY"
 
-# Check if Container exists
-echo "===> Checking if Container '$ST_FILESYSTEM' exists."
-if az storage container exists --name "$ST_FILESYSTEM" -o tsv | grep -q "True"; then
-    echo "===> Container '$ST_FILESYSTEM' exists."
+# Check if Directory exists
+echo "===> Checking if Directory '$DIR' exists..."
+if az storage fs directory exists --file-system "$ST_CONTAINER" --name "$DIR" -o tsv | grep -q "True"; then
+    echo "===> Directory '$DIR' exists."
 else
-    echo "===> Container does not exists so creating container '$ST_FILESYSTEM'."
-    az storage container create --name "$ST_FILESYSTEM" || die "Failed to create Container '$ST_FILESYSTEM'."
-    echo "===> Container '$ST_FILESYSTEM' created."
-fi
+    die "Failed to create Directory '$DIR'."
+fi  
 
 echo "===> Checking if database '$DB_NAME' exists on host '$DB_HOST'."
 DB_EXISTS=$(mysql -h "$DB_HOST" -u"$DB_ADMIN" -p"$DB_PASS" --skip-column-names -e "SHOW DATABASES LIKE '$DB_NAME'") || die "Failed to connect to MySQL."
@@ -70,8 +69,9 @@ if [[ "$DB_EXISTS" == "$DB_NAME" ]]; then
     echo "$BACKUP_FILE" > checkin.txt
 
     echo "===> Uploading database backup to Azure Blob Storage."
-    az storage blob upload --container-name "$ST_FILESYSTEM" --file "$BACKUP_FILE.tar.gz" --name "$BACKUP_FILE.tar.gz" --overwrite || die "Backup upload failed."
-    az storage blob upload --container-name "$ST_FILESYSTEM" --file "checkin.txt" --name "checkin.txt" --overwrite || die "Checkin file upload failed."
+    az storage blob upload --container-name "$ST_CONTAINER" --file "$BACKUP_FILE.tar.gz" --name "$BACKUP_FILE.tar.gz" --overwrite || die "Backup upload failed."
+    echo "===> Checkin file upload to Azure Blob Storage."
+    az storage blob upload --container-name "$ST_CONTAINER" --file "checkin.txt" --name "checkin.txt" --overwrite || die "Checkin file upload failed."
     echo "===> Database backup '$BACKUP_FILE' uploaded successfully."
 
     # Cleanup
diff --git a/scripts/db-restore b/scripts/db-restore
--- a/scripts/db-restore
+++ b/scripts/db-restore
@@ -12,7 +12,7 @@ die () {
 
 # Function for script usage
 usage () {
-    echo "Usage: $0 --host <host> --admin <admin> --password <admin_pass> --dbname <db_name> --staccount <st_account> --stkey <st_key> --stcontainer <st_container>"
+    echo "Usage: $0 --host <host> --admin <admin> --password <admin_pass> --scrdbname <src_db_name> --srcstaccount <src_st_account> --srcstkey <src_st_key> --srcstcontainer <src_st_container> --dstdbname <dst_db_name> --dststaccount <dst_st_account> --dststkey <dst_st_key> --dststcontainer <dst_st_container>"
     exit 1
 }
 
@@ -22,17 +22,21 @@ while [[ $# -gt 0 ]]; do
         --host) DB_HOST="$2"; shift 2;;
         --admin) DB_ADMIN="$2"; shift 2;;
         --password) DB_PASS="$2"; shift 2;;
-        --dbname) DB_NAME="$2"; shift 2;;
-        --staccount) ST_ACCOUNT="$2"; shift 2;;
-        --stkey) ST_KEY="$2"; shift 2;;
-        --stcontainer) ST_FILESYSTEM="$2"; shift 2;;
+        --srcdbname) SRC_DB_NAME="$2"; shift 2;;
+        --srcstaccount) SRC_ST_ACCOUNT="$2"; shift 2;;
+        --srcstkey) SRC_ST_KEY="$2"; shift 2;;
+        --srcstcontainer) SRC_ST_FILESYSTEM="$2"; shift 2;;
+        --dstdbname) DST_DB_NAME="$2"; shift 2;;
+        --dststaccount) DST_ST_ACCOUNT="$2"; shift 2;;
+        --dststkey) DST_ST_KEY="$2"; shift 2;;
+        --dststcontainer) DST_ST_FILESYSTEM="$2"; shift 2;;
         --help) usage;;
         *) die "Unknown option: $1";;
     esac
 done
 
 # Validate required parameters
-if [[ -z "${DB_HOST:-}" || -z "${DB_ADMIN:-}" || -z "${DB_PASS:-}" || -z "${DB_NAME:-}" || -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_FILESYSTEM:-}" ]]; then
+if [[ -z "${DB_HOST:-}" || -z "${DB_ADMIN:-}" || -z "${DB_PASS:-}" || -z "${$SCR_DB_NAME}" ||  -z "${$SRC_ST_ACCOUNT}"  || -z "${$SRC_ST_KEY}" || -z "${$SRC_ST_FILESYSTEM}" || -z "${$DST_DB_NAME}" || -z "${$DST_ST_ACCOUNT}" || -z "${$DST_ST_KEY}" || -z "${$DST_ST_FILESYSTEM}" ]]; then  
     die "Missing required parameters."
 fi
 
@@ -41,22 +45,25 @@ export AZURE_STORAGE_ACCOUNT="$ST_ACCOUNT"
 export AZURE_STORAGE_KEY="$ST_KEY"
 
 # Check if Container exists
-echo "===> Checking if Container '$ST_FILESYSTEM' exists..."
-if az storage container exists --name "$ST_FILESYSTEM" -o tsv | grep -q "True"; then
-    echo "===> Container '$ST_FILESYSTEM' exists."
+echo "===> Checking if Container '$SRC_ST_FILESYSTEM' exists..."
+if az storage container exists --name "$SRC_ST_FILESYSTEM" -o tsv | grep -q "True"; then
+    echo "===> Container '$SRC_ST_FILESYSTEM' exists."
 else
     die "Container '$ST_FILESYSTEM' does not exists."
 fi
 
-echo "===> Checking if database '$DB_NAME' exists on host '$DB_HOST'..."
-DB_EXISTS=$(mysql -h "$DB_HOST" -u"$DB_ADMIN" -p"$DB_PASS" --skip-column-names -e "SHOW DATABASES LIKE '$DB_NAME'") || die "Failed to connect to MySQL."
+echo "===> Checking if database '$DST_DB_NAME' exists on host '$DB_HOST'..."
+DB_EXISTS=$(mysql -h "$DB_HOST" -u"$DB_ADMIN" -p"$DB_PASS" --skip-column-names -e "SHOW DATABASES LIKE '$DST_DB_NAME'") || die "Failed to connect to MySQL."
 
-if [[ "$DB_EXISTS" == "$DB_NAME" ]]; then
-    echo "===> Database '$DB_NAME' exists. Proceeding with restore..."
+if [[ "$DB_EXISTS" == "$DST_DB_NAME" ]]; then
+    echo "===> Database '$DST_DB_NAME' exists. Proceeding with restore..."
+    
+    #Backup the database
+    db-dump --host "$DB_HOST" --admin "$DB_ADMIN" --password "$DB_PASS" --dbname "$DST_DB_NAME" --staccount "$DST_ST_ACCOUNT" --stkey "$DST_ST_KEY" --stcontainer "$DST_ST_FILESYSTEM" || die "Failed to backup database."
 
     # Download checkin.txt
     echo "===> Downloading 'checkin.txt' from Azure Storage..."
-    az storage blob download --container-name "$ST_FILESYSTEM" --name "checkin.txt" --file "checkin.txt" --overwrite || die "Failed to download checkin.txt."
+    az storage blob download --container-name "$SRC_ST_FILESYSTEM" --name "checkin.txt" --file "checkin.txt" --overwrite || die "Failed to download checkin.txt."
 
     # Read the database dump name
     if [[ ! -f checkin.txt ]]; then
@@ -65,7 +72,7 @@ if [[ "$DB_EXISTS" == "$DB_NAME" ]]; then
     BACKUP_FILE=$(cat checkin.txt)
 
     echo "===> Downloading database dump '$BACKUP_FILE.tar.gz'..."
-    az storage blob download --container-name "$ST_FILESYSTEM" --name "$BACKUP_FILE.tar.gz" --file "$BACKUP_FILE.tar.gz" || die "Failed to download database dump."
+    az storage blob download --container-name "$SRC_ST_FILESYSTEM" --name "$BACKUP_FILE.tar.gz" --file "$BACKUP_FILE.tar.gz" || die "Failed to download database dump."
 
     echo "===> Extracting database dump..."
     tar -xzvf "$BACKUP_FILE.tar.gz" || die "Failed to extract database dump."
@@ -76,9 +83,9 @@ if [[ "$DB_EXISTS" == "$DB_NAME" ]]; then
     fi
 
     echo "===> Restoring database from '$BACKUP_FILE'..."
-    mysql -h "$DB_HOST" -u"$DB_ADMIN" -p"$DB_PASS" "$DB_NAME" < "$BACKUP_FILE" || die "Database restore failed."
+    mysql -h "$DB_HOST" -u"$DB_ADMIN" -p"$DB_PASS" "$DST_DB_NAME" < "$BACKUP_FILE" || die "Database restore failed."
 
-    echo "===> Database '$DB_NAME' restore completed successfully."
+    echo "===> Database '$DST_DB_NAME' restore completed successfully."
 else
-    echo "===> Database '$DB_NAME' does not exist. Skipping restore."
+    echo "===> Database '$DST_DB_NAME' does not exist. Skipping restore."
 fi
diff --git a/scripts/fs-create b/scripts/fs-create
--- a/scripts/fs-create
+++ b/scripts/fs-create
@@ -12,7 +12,7 @@ die () {
 
 # Usage function
 usage () {
-    echo "Usage: $0 --staccount <st_account> --stkey <st_key> --stfilesystem <st_filesystem> --dir <dir> --file <file>"
+    echo "Usage: $0 --staccount <st_account> --stkey <st_key> --stfileshare <st_fileshare> --dir <dir> --file <file>"
     exit 1
 }
 
@@ -21,7 +21,7 @@ while [[ $# -gt 0 ]]; do
     case "$1" in
         --staccount) ST_ACCOUNT="$2"; shift 2;;
         --stkey) ST_KEY="$2"; shift 2;;
-        --stfilesystem) ST_FILESYSTEM="$2"; shift 2;;
+        --stfileshare) ST_FILESHARE="$2"; shift 2;;
         --dir) DIR="$2"; shift 2;;
         # --file) FILE="$2"; shift 2;;
         --help) usage;;
@@ -30,7 +30,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 # Validate required parameters
-if [[ -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_FILESYSTEM:-}" || -z "${DIR:-}" ]]; then
+if [[ -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_FILESHARE:-}" || -z "${DIR:-}" ]]; then
     die "Missing parameters."
 fi
 
@@ -39,41 +39,21 @@ export AZURE_STORAGE_ACCOUNT="$ST_ACCOUNT"
 export AZURE_STORAGE_KEY="$ST_KEY"
 
 # Check if Fileshare exists
-echo "===> Checking if Fileshare '$ST_FILESYSTEM' exists."
-if az storage share exists --name "$ST_FILESYSTEM" -o tsv | grep -q "True"; then
-    echo "===> Fileshare '$ST_FILESYSTEM' exists."
+echo "===> Checking if Fileshare '$ST_FILESHARE' exists."
+if az storage share exists --name "$ST_FILESHARE" -o tsv | grep -q "True"; then
+    echo "===> Fileshare '$ST_FILESHARE' exists."
 else
-    echo "===> Fileshare does not exists so creating Fileshare '$ST_FILESYSTEM'."
-    az storage share create --name "$ST_FILESYSTEM" || die "Failed to create Fileshare '$ST_FILESYSTEM'."
-    echo "===> Fileshare '$ST_FILESYSTEM' created."
+    echo "===> Fileshare does not exists so creating Fileshare '$ST_FILESHARE'."
+    az storage share create --name "$ST_FILESHARE" || die "Failed to create Fileshare '$ST_FILESHARE'."
+    echo "===> Fileshare '$ST_FILESHARE' created."
 fi
 
 # Check if Directory exists
 echo "===> Checking if Directory '$DIR' exists..."
-if az storage directory exists --share-name "$ST_FILESYSTEM" --name "$DIR" -o tsv | grep -q "True"; then
+if az storage directory exists --share-name "$ST_FILESHARE" --name "$DIR" -o tsv | grep -q "True"; then
     echo "===> Directory '$DIR' exists."
 else
     echo "===> Directory does not exists so creating Directory '$DIR'."
-    az storage directory create --share-name "$ST_FILESYSTEM" --name "$DIR" || die "Failed to create Directory '$DIR'."
-    echo "===> Directory '$DIR' created."
-fi  
-
-# Check if Container exists
-echo "===> Checking if Container '$ST_FILESYSTEM' exists..."
-if az storage container exists --name "$ST_FILESYSTEM" -o tsv | grep -q "True"; then
-    echo "===> Container '$ST_FILESYSTEM' exists."
-else
-    echo "===> Container does not exists so creating container '$ST_FILESYSTEM'."
-    az storage container create --name "$ST_FILESYSTEM" || die "Failed to create Container '$ST_FILESYSTEM'."
-    echo "===> Container '$ST_FILESYSTEM' created."
-fi
-
-# Check if Directory exists
-echo "===> Checking if Directory '$DIR' exists..."
-if az storage fs directory exists --file-system "$ST_FILESYSTEM" --name "$DIR" -o tsv | grep -q "True"; then
-    echo "===> Directory '$DIR' exists."
-else
-    echo "===> Directory does not exists so creating Directory '$DIR' on ."
-    az storage fs directory create --file-system "$ST_FILESYSTEM" --name "$DIR" || die "Failed to create Directory '$DIR'."
+    az storage directory create --share-name "$ST_FILESHARE" --name "$DIR" || die "Failed to create Directory '$DIR'."
     echo "===> Directory '$DIR' created."
 fi  
diff --git a/scripts/fs-upload b/scripts/fs-upload
--- a/scripts/fs-upload
+++ b/scripts/fs-upload
@@ -12,7 +12,7 @@ die () {
 
 # Usage function
 usage () {
-    echo "Usage: $0 --staccount <st_account> --stkey <st_key> --stfilesystem <st_filesystem> --dir <dir> --file <file>"
+    echo "Usage: $0 --staccount <st_account> --stkey <st_key> --stfileshare <st_fileshare> --dir <dir> --file <file>"
     exit 1
 }
 
@@ -21,7 +21,7 @@ while [[ $# -gt 0 ]]; do
     case "$1" in
         --staccount) ST_ACCOUNT="$2"; shift 2;;
         --stkey) ST_KEY="$2"; shift 2;;
-        --stfilesystem) ST_FILESYSTEM="$2"; shift 2;;
+        --stfileshare) ST_FILESHARE="$2"; shift 2;;
         --dir) DIR="$2"; shift 2;;
         --file) FILE="$2"; shift 2;;
         --help) usage;;
@@ -30,7 +30,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 # Validate required parameters
-if [[ -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_FILESYSTEM:-}" || -z "${DIR:-}" || -z "${FILE:-}" ]]; then
+if [[ -z "${ST_ACCOUNT:-}" || -z "${ST_KEY:-}" || -z "${ST_FILESHARE:-}" || -z "${DIR:-}" || -z "${FILE:-}" ]]; then
     die "Missing parameters."
 fi
 
@@ -39,16 +39,16 @@ export AZURE_STORAGE_ACCOUNT="$ST_ACCOUNT"
 export AZURE_STORAGE_KEY="$ST_KEY"
 
 # Check if Fileshare exists
-echo "===> Checking if Fileshare '$ST_FILESYSTEM' exists."
-if az storage share exists --name "$ST_FILESYSTEM" -o tsv | grep -q "True"; then
-    echo "===> Fileshare '$ST_FILESYSTEM' exists."
+echo "===> Checking if Fileshare '$ST_FILESHARE' exists."
+if az storage share exists --name "$ST_FILESHARE" -o tsv | grep -q "True"; then
+    echo "===> Fileshare '$ST_FILESHARE' exists."
 else
-    die "Fileshare '$ST_FILESYSTEM' does not exists."
+    die "Fileshare '$ST_FILESHARE' does not exists."
 fi
 
 # Check if Directory exists
-echo "===> Checking if Directory '$DIR' exists on Fileshare '$ST_FILESYSTEM'"
-if az storage directory exists --share-name "$ST_FILESYSTEM" --name "$DIR" -o tsv | grep -q "True"; then
+echo "===> Checking if Directory '$DIR' exists on Fileshare '$ST_FILESHARE'"
+if az storage directory exists --share-name "$ST_FILESHARE" --name "$DIR" -o tsv | grep -q "True"; then
     echo "===> Directory '$DIR' exists."
 else
     die "Directory '$DIR' does not exists."
@@ -56,10 +56,10 @@ fi
 
 # Check if File exists
 echo "===> Checking if File '$FILE' exists."
-if az storage file exists --share-name "$ST_FILESYSTEM" --path "$DIR/$FILE" -o tsv | grep -q "True"; then
+if az storage file exists --share-name "$ST_FILESHARE" --path "$DIR/$FILE" -o tsv | grep -q "True"; then
     echo "===> File '$FILE' already exists."
 else
     echo "===> File does not exists so uploading File '$FILE'."
-    az storage file upload --share-name "$ST_FILESYSTEM" --source "$FILE" --path "$DIR/$FILE" || die "Failed to upload File '$FILE'."
+    az storage file upload --share-name "$ST_FILESHARE" --source "$FILE" --path "$DIR/$FILE" || die "Failed to upload File '$FILE'."
     echo "===> File '$FILE' uploaded."
 fi
